<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128047;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128049;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128057;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128054;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128569;</a>


<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128571;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128572;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128573;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128574;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128575;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128576;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128584;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128585;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128586;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128000;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128001;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128002;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128003;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128004;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128005;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128006;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128007;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128008;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128009;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128010;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128011;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128012;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128013;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128014;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128015;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128016;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128017;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128018;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128019;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128020;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128021;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128022;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128023;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128024;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128025;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128026;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128027;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128028;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128029;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128030;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128031;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128032;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128033;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128034;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128035;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128036;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128037;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128038;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128039;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128040;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128041;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128042;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128043;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128044;</a>