<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128641;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128642;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128643;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128644;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128645;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128646;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128647;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128648;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128649;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128650;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128651;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128652;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128653;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128654;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128655;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128656;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128657;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128658;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128659;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128660;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128661;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128662;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128663;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128664;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128665;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128666;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128667;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128668;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128669;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128670;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128671;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128672;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128673;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128674;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128675;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128676;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128739;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128740;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128741;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128745;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128747;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128748;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128752;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128755;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128756;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128757;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128758;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128759;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128760;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128761;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128680;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128681;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128682;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128683;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128684;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128685;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128686;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128687;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128688;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128689;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128690;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128691;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128692;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128693;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128694;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128695;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128696;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128697;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128698;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128699;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128700;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128701;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128702;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128703;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128704;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128705;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128706;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128707;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128708;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128709;</a>


