<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127813;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127814;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127815;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127816;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127817;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127818;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127819;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127820;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127821;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127822;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127823;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127824;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127825;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127826;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127827;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127828;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127829;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127830;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127831;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127832;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127833;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127834;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127835;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127836;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127837;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127838;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127839;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127840;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127841;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127842;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127843;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127844;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127845;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127846;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127847;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127848;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127849;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127850;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127851;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127852;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127853;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127854;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127855;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127856;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127857;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127858;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127859;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127860;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127861;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127862;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127863;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127864;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127865;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127866;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127867;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127868;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127869;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127870;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127871;</a>