<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#8986;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#8987;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9193;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127386;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9194;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9195;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9196;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9197;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9198;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9199;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9200;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9201;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9202;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9203;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9208;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9209;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9210;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#10071;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#10133;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#10134;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#10160;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#10175;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127374;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127377;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127378;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127379;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127380;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127381;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127382;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127383;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127384;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127385;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127514;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127535;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127538;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127539;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9748;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9800;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9801;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9802;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9803;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9804;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9805;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9806;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9807;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9808;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9809;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9810;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9811;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9855;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9875;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9889;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9898;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9899;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9917;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9918;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9924;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9925;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9934;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9935;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9937;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9939;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9940;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9961;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9969;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9970;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9971;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9972;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9973;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9975;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9976;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9977;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9978;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9981;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9989;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#10062;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#10067;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#10068;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#10069;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127540;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127541;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127542;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127544;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127545;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127546;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127568;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127569;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127757;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127758;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127759;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127760;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127761;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127762;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127763;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127764;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127765;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127766;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127767;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127768;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127769;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127770;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127771;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127772;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127773;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127774;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127775;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127776;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127777;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127780;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127781;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127782;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127783;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127784;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127785;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127786;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127787;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127788;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127793;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127794;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127795;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127796;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127797;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127800;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127801;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127802;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127803;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127804;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127805;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127806;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127807;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127808;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127809;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127810;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127811;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127812;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127344;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127345;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127358;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127387;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127388;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#127389;</a>
