<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128512;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128513;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128514;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128515;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128516;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128517;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128518;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128519;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128520;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128521;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128522;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128523;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128524;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128525;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128526;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128527;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128528;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128529;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128530;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128531;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128532;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128533;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128534;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128535;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128536;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128537;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128538;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128539;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128540;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128541;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128542;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128543;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128544;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128545;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128546;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128547;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128548;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128549;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128551;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128552;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128553;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128554;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128555;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128556;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128557;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128558;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128559;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128560;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128561;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128562;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128563;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128564;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128565;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128566;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128567;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128577;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128578;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128579;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128580;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128581;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128582;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128583;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128587;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128400;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128405;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128406;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128588;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9994;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9995;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9996;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128070;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128071;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128072;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128073;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128074;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128075;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128076;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128170;</a>

<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128078;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128079;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128080;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#9997;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128064;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128065;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128066;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128067;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128068;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128069;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128102;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128103;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128104;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128105;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128106;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128107;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128108;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128109;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128110;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128111;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128112;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128113;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128114;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128115;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128116;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128117;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128118;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128119;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128120;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128124;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128129;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128130;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128131;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128132;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128133;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128134;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128135;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128139;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128145;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128143;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#129335;</a>

<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128420;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128147;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128148;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128149;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128150;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128151;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128152;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128153;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128154;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128155;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128156;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128157;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128158;</a>
<a href="javascript:void(0)"  class='far' onclick="getEmoji(this);">&#128159;</a>